### ISSUE TITLE
Can't setup airtable

### ISSUE THREAD

**Issue by antonijap** [zeroxme/dark-vader-issues#1]
![image](https://user-images.githubusercontent.com/12565719/140917257-f24f3a9c-79e6-4033-a185-6288dda3c734.png)

I just have a spinner, and modal never opens

**Comment by zeroxme** [comment]
Hi Antonija,

Thanks so much for reaching out 🥳
To help me understand the problem better can you please provide the following

1. Provide a link to your AirTable sheet
2. Add a screenshot of the console error. Go to `Plugins > Development > Open console`

**Comment by antonijap** [comment]
I didn't even get to Airtable sheet.

![image](https://user-images.githubusercontent.com/12565719/140923482-e0a284f9-224c-48d7-a9ef-0073005bbacb.png)

**Comment by zeroxme** [comment]
yeah but that's the thing... u need to setup AirTable with your style IDs and then use the plugin to convert
here's a guide for how to do that https://github.com/zeroxme/dark-vader-issues#how-it-works

Please let me know if you need further help or in setting up your styles... I wouldn't mind jumping in the file to help too :D maybe a sample one that u can share `me@zerox.me` .. who knows.. maybe there's a bug somewhere :D

**Comment by zeroxme** [comment]
Did you select designs or frames with published team styles? if it's local styles that might be why it's not working 🤔

**Comment by zeroxme** [comment]
@antonijap I managed to reproduce the same exact error... I guess I worked on it based on the assumption of team library/styles... should be easy to fix so I'm on it... this feedback is awesome! I really appreciate it so much 🤩
<img width="805" alt="Screenshot 2021-11-09 at 4 27 28 pm" src="https://user-images.githubusercontent.com/3534296/140953230-9e2fdb0a-0e4a-4efa-9709-0ed59446f00a.png">

**Comment by zeroxme** [comment]
@antonijap just pushed a fix... please, let me know if it breaks again

**Comment by antonijap** [comment]
Good job, now the modal is opening!

**Comment by zeroxme** [comment]
I'm so glad it worked 🤩 keep the feedback coming 😇 ... did everything else work fine?
